extends Node
var tick: Timer
var tick_count: int = 0
@onready var tick_process: TickProcess = TickProcess.new()

func _ready():
	#var simulator = UnlockSimulator.new()
	#add_child(simulator)
	Unlocks.apply_modifiers()
	setup_tick_timer()

func setup_tick_timer():
	tick = Timer.new()
	tick.wait_time = 1.0
	tick.connect("timeout", _on_tick_timeout)
	add_child(tick)
	tick.start()

func _on_tick_timeout():
	tick_count += 1
	tick_process.tick()
	Log.pr("Tick", str(tick_count))
	Log.pr("Current Currency:", Inventory.get_currency())
